name: .NET Core Desktop

on: workflow_dispatch

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Project_Name: DormPuzzle\DormPuzzle.csproj
      Build_Path: ${{ github.workspace }}\Build\DormPuzzle
      Publish_Path: ${{ github.workspace }}\Publish

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Build the application
    - name: Build the application
      run: msbuild $env:Project_Name /t:Build /p:Configuration=$env:Configuration /p:OutputPath=$env:Build_Path
      env:
        Configuration: ${{ matrix.configuration }}

    # Zip the build output
    - name: Zip the build output
      run: 7z a -tzip $env:Publish_Path\DormPuzzle.zip $env:Build_Path

    # Publish the build output
    - name: Publish the build output
      uses: softprops/action-gh-release@v2.0.5
      with:
        draft: true
        files: |
          ./Publish/*.zip
