name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Project_Name: DormPuzzle\DormPuzzle.csproj
      Publish_Name: Publish\DormPuzzle.zip
      Build_Output: Build\DormPuzzle\

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Build the application
    - name: Build the application
      run: msbuild $env:Project_Name /t:Build /p:Configuration=$env:Configuration /p:OutputPath=$env:Build_Output
      env:
        Configuration: ${{ matrix.configuration }}

    # Zip the build output
    - name: Zip the build output
      run: 7z a -tzip $env:Publish_Name $env:Build_Output

    # Release the build output
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        draft: true
        files: |
          ./Publish/*.zip